### ISSUE TITLE
Title tag could also be a part of the frontmatter

### ISSUE THREAD

**Issue by lsolesen** [schultyy/better-seo#117]
In Jekyll the title tag is not the first level heading in the body, but specified in the frontmatter. It would be useful, if this was also supported.

Could also be useful if it could analyze more SEO metrics.

**Comment by schultyy** [comment]
Oh, that's good to know. I'll add that to my to-do list! 

Re SEO Metrics: Do you have specific metrics in mind?

**Comment by schultyy** [comment]
@lsolesen I just released better-seo 2.0.0 which allows for the title being defined in frontmatter. You can configure the `title` field in the editor settings.

**Comment by schultyy** [comment]
Implemented this ticket. Closing.
